### PR TITLE
[FLINK-26703] Introduce flink-table-store-dist module for packaging

### PR DESCRIPTION
**Pull request by tsreaper**
We need a flink-table-store-dist module to produce a fat connector jar for table store.

### CODE REVIEW

**Comment by JingsongLi** [comment]
- We can check the classes in the bundle jar. Let's see if we can shade more, For example, orc has hive-related dependencies inside.
- We should introduce NOTICE file?

**Comment by tsreaper** [comment]
Hive related dependencies are already shaded. I'll take a look at the NOTICE file.

**Comment by JingsongLi** [comment]
`org/apache/hadoop/hive` needs to be shaded too

**Review by JingsongLi — APPROVED** [review]
Looks good to me!

**Pull request merged**
