### PR TITLE
[FLINK-29832] Refactor default database name to default_database

### PR DESCRIPTION
**Pull request by zjureel**
Add create and use `default` database in start docs

### CODE REVIEW

**Comment by zjureel** [comment]
Hi @tsreaper I have updated this issue, what do you think of it? THX

**Comment by LadyForest** [comment]
Actually, `default` is a keyword in SQL, and one should escape it when referring it. 
E.g. 
```sql
SELECT * FROM table_store.`default`.my_table
```

**Comment by SteNicholas** [comment]
@zjureel, the default database is always `default` in common catalog like `HoodieCatalog`. The users could use the above way to solve the issue you mentioned.

**Comment by zjureel** [comment]
Thanks @LadyForest @SteNicholas I closed this PR :)

**Pull request closed without merging**
